### ISSUE TITLE
想问下python版本是多少

### ISSUE THREAD

**Issue by MurphySongAI** [orion-orion/Community-Detection-MTFL#1]
python3.8装 scikit-learn==1.1.0的时候报错 找不到

**Comment by orion-orion** [comment]
Sorry，是我没在README里写清楚，我跑这个项目的Python版本为3.8.12，目前已在README中说明。实在不行的话你scikit-learn随便选一个版本装问题应该不大，这个项目只用了scikit-learn的`train_test_split`函数和`AgglomerativeClustering`算法

**Comment by takahirosir** [comment]
您的来信已收到，我会及时认真查看，谢谢！

**Comment by MurphySongAI** [comment]
收到,感谢~
