### ISSUE TITLE
跑Shakespeare数据集的时候报错

### ISSUE THREAD

**Issue by MurphySongAI** [orion-orion/Community-Detection-MTFL#2]
PermissionError: [WinError 5] 拒绝访问。: './data\\Shakespeare\\temp' -> './data\\Shakespeare\\all_data'

我看了一下因为别的数据集基本都是文件夹线面就是train和test的数据，但是Shakespeare下面有temp和raw两个文件夹，temp下面有1000多个client文件夹，不知道应该用哪个数据呀？应该是用raw里面的which one？

**Comment by orion-orion** [comment]
你好，你这是Windows路径和Linux路径不兼容的问题，你需要在Linux/Mac系统下运行这个项目喔~关于数据的问题，Shakespeare数据集本身含有1144个client的数据，我们只需要选择前n_clients个来使用（比如前10个）即可，这部分我的代码已经帮你做了，你不用修改。

**Comment by takahirosir** [comment]
您的来信已收到，我会及时认真查看，谢谢！

**Comment by MurphySongAI** [comment]
明白了，感谢🙂

**Comment by orion-orion** [comment]
> 明白了，感谢🙂

🤝
